# Generated by Django 3.2.2 on 2021-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('image', models.ImageField(blank=True, upload_to='img', verbose_name='картинка')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
